### ISSUE TITLE
__BUILD_VERSION__ constant

### ISSUE THREAD

**Issue by mpivaa** [ecostage/generator-prelude#1]
@ecostage/developers estava eu usando localStorage para guardar coisas pesadas para que o usuário não tenha que baixar toda vez quando entrar no site, mas assim que atualizo a versão do sistema não existe uma forma fácil de resetar o localStorage dos clients. Acredito que uma build version definida randomicamente nos ajude a saber quando mudou a versão.

``` js
new webpack.DefinePlugin({
  __BUILD_VERSION__: JSON.stringify(uuid.v4())
})
```

**Comment by mateusmedeiros** [comment]
Ótima ideia :+1: 

Hoje de tarde se tiver tempo vou ver se implemento isso e corrijo alguns dos problemas que eu tive com Kaio.
